### ISSUE TITLE
add support for configura data folder

### ISSUE THREAD

**Issue by hepin1989** [Graylog2/omnibus-graylog2#14]
eg: I want to put all the data in folder of ```/data```

**Comment by mariussturm** [comment]
Could you please elaborate a little bit more on this? What is the use case? Why is it not possible to over-mount /opt/data?

**Comment by hepin1989** [comment]
@mariussturm we a running it at http://www.qcloud.com/,and the data disk is always mounted at /data.
and the system disk is free but small.

I have change the configuration manually to point it to /data,maybe it's not a problem when running it with aws.:)

thanks

**Comment by hepin1989** [comment]
what I am asking it when run graylog-ctl reconfigura,
it would promote a cli inputing that asking where shoudl graylog saving data:)

**Comment by mariussturm** [comment]
The latest omnibus package allows you to overwrite all chef attributes through the settings file `/etc/graylog/graylog-settings.json`. Take a look here for all attributes: https://github.com/Graylog2/omnibus-graylog2/blob/1.1/files/graylog-cookbooks/graylog/attributes/default.rb

For example if you want to change the Graylog user, you can edit `graylog-settings.json` to the following:

```
"custom_attributes": {
    "user": {
      "username": "log-user"
    }
  }
```

Afterwards run `sudo graylog-ctl reconfigure` and `sudo chown -R log-user /var/opt/graylog/data/*`

To change the data-path edit the file to this:
```
"custom_attributes": {
    "elasticsearch": {
      "data_directory": "/data/elasticsearch"
    },
    "mongodb": {
      "data_directory": "/data/mongodb"
    },
    "etcd": {
      "data_directory": "/data/etcd"
    },
    "graylog-server": {
      "journal_directory": "/data/journal"
    }
  }
```
Again, afterwards run `sudo graylog-ctl reconfigure`

In this way you can persist your custom changes but still be able to update the package und run reconfigure without reverting your changes.
