### ISSUE TITLE
enhance the custom_attributes support for tuning Elasticsearch & graylog

### ISSUE THREAD

**Issue by hepin1989** [Graylog2/omnibus-graylog2#17]
the[ Configuring and tuning Elasticsearch](http://docs.graylog.org/en/1.1/pages/configuring_es.html) describe how to make the graylog production read,I think it should be great to add support for this in the ```custom_attributes``` support.
eg :
- cluster name(es&graylog)
- discovery mode(es&graylog)
- heapsize(es&graylog)
- message_journal_max_size(graylog)
- async_eventbus_processors(graylog)
- message_journal_max_age(graylog)
thanks.

**Comment by mariussturm** [comment]
Heapsize can now be set through custom attributes like: 
```
"custom_attributes": {
    "graylog-server": {
      "memory": "1700m"
    },
    "elasticsearch": {
      "memory": "2200m"
    }
  }
```
Journal size can be set through `graylog-ctl`, have a look here: http://docs.graylog.org/en/1.2/pages/installation/graylog_ctl.html#configure-message-retention

For full customization please consider a manual installation or rather a supported installation with Chef or Puppet.
