### ISSUE TITLE
Dangerous graylog.conf default

### ISSUE THREAD

**Issue by joschi** [Graylog2/omnibus-graylog2#18]
Copied from Graylog2/graylog2-server#1420

> 'retention_strategy'
Chef defaults this to 'delete'. That means in an otherwise clean environment, a `graylog-ctl reconfigure` can cause data loss as it immediately restarts graylog-server and may start deleting indices. Suggest that this option be moved to be configurable from /etc/graylog/graylog-settings.json

@voodoodrul Please subscribe to this issue.

**Comment by hepin1989** [comment]
we change to close,and change it to time based one.

**Comment by mariussturm** [comment]
Please update to the latest omnibus package. I have made a bunch of attributes configurable. To change the retention strategy please edit `/etc/graylog/graylog-settings.json` to the following:

```
"custom_attributes": {
    "graylog-server": {
      "retention_strategy": "close"
    }
  }
```

@hepin1989 please also have a look at https://github.com/Graylog2/omnibus-graylog2/blob/1.2/files/graylog-cookbooks/graylog/attributes/default.rb
There is now a lot of stuff you were asking for!

**Comment by voodoodrul** [comment]
This is fantastic. Thank you!
