### ISSUE TITLE
elasticsearch_max_time_per_index = 1dh

### ISSUE THREAD

**Issue by renapu** [Graylog2/omnibus-graylog2#19]
"elasticsearch_max_time_per_index" always gets an "h" at the end, because of the template.

**Comment by mariussturm** [comment]
That's right and documented here: http://docs.graylog.org/en/1.3/pages/installation/graylog_ctl.html#configure-message-retention

Without forcing a unit people tried all kind of values like without any unit, up case, lower case, random characters. This seams most convenient for most users.
