### ISSUE TITLE
Debian Wheezy, 7.8, GLIBC 2.14/2.17 not satisfied

### ISSUE THREAD

**Issue by LordMike** [Graylog2/omnibus-graylog2#2]
Hey,

A fresh install of the "latest" deb package yields a "/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found" error when running graylog2-ctl. The same file requiring 2.14 also requires 2.17, weirdly enough.

Currently, as of stable, I have libc6 2.13 installed.

It seems to be the embedded ruby install requiring it. Complete error:

    # graylog2-ctl
    /opt/graylog2/embedded/bin/ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /opt/graylog2/embedded/lib/libruby.so.2.1)
    /opt/graylog2/embedded/bin/ruby: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /opt/graylog2/embedded/lib/libruby.so.2.1)

**Comment by LordMike** [comment]
I hacked my way around it by installing libc6 from Sids repositories. Probably not a recommended workaround.

http://stackoverflow.com/a/21254623/1246988

**Comment by mariussturm** [comment]
The package was build for Ubuntu 14.04, does it happen there as well?

**Comment by LordMike** [comment]
Presumably not - becuse Trusty has Glibc 2.19
http://packages.ubuntu.com/trusty/libc6

**Comment by LordMike** [comment]
Just confirmed. Works in Ubuntu 14.04 LTS as expected.

**Comment by mariussturm** [comment]
Ok, cool. Thanks for double checking!
I have add a note that the package is only for Ubuntu. If there are more people interested in a Debian package we could setup a special build environment for that. Please leave a comment here if you are interested.

**Comment by LordMike** [comment]
My entire server-setup (13 vms at home) is Debian. We run Debian at work too, so yea, I'd be interested. :).
