### ISSUE TITLE
CentOS 7 Support

### ISSUE THREAD

**Issue by jaxxstorm** [Graylog2/omnibus-graylog2#23]
CentOS 7 has been around for a while now, and plans to support packages for it?

**Comment by joschi** [comment]
@jaxxstorm There are already official Graylog packages for CentOS 7 (see http://docs.graylog.org/en/1.3/pages/installation/operating_system_packages.html#centos-7). The omnibus package will only support Ubuntu Linux (as it's being used in the virtual machine, Docker, and Amazon images).
