### ISSUE TITLE
Install Elasticsearch Kopf by default

### ISSUE THREAD

**Issue by joschi** [Graylog2/omnibus-graylog2#24]
In order to quickly check the status of the Elasticsearch cluster and run some quick queries, the [Kopf](https://github.com/lmenezes/elasticsearch-kopf) plugin is very useful.

Since users aren't supposed to manually install Elasticsearch plugins in the virtual machine and Docker images, this plugin should be installed by default.

**Comment by renapu** [comment]
:+1:

**Comment by mariussturm** [comment]
This will be part of the next release!
