### ISSUE TITLE
Compile error in ncurses dependency 

### ISSUE THREAD

**Issue by Aleyasen** [Graylog2/omnibus-graylog2#25]
I tried to build graylog using below command:
sudo bin/omnibus build graylog

I got the following error that is related to compiling ncurses. 

[Builder: ncurses] W | [1/1] Failed to execute command. Retrying in 10 seconds...
/var/lib/gems/2.1.0/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:272:in `invalid!': Expected process to exit with [0], but received '2' (Mixlib::ShellOut::ShellCommandFailed)
---- Begin output of make -j 9 ----
STDOUT: cd man && make DESTDIR="" all
make[1]: Entering directory '/var/cache/omnibus/src/ncurses-5.9/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/var/cache/omnibus/src/ncurses-5.9/man'
cd include && make DESTDIR="" all
make[1]: Entering directory '/var/cache/omnibus/src/ncurses-5.9/include'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/var/cache/omnibus/src/ncurses-5.9/include'
cd ncurses && make DESTDIR="" all
make[1]: Entering directory '/var/cache/omnibus/src/ncurses-5.9/ncurses'
sh -e ./tinfo/MKcaptab.sh mawk 1 ./tinfo/MKcaptab.awk ./../include/Caps > comp_captab.c
mawk -f ./base/MKkeyname.awk bigstrings=1 keys.list > lib_keyname.c
gcc -o make_keys -DHAVE_CONFIG_H -I../ncurses -I. -I./../include -I../include -DUSE_BUILD_CC -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 ./tinfo/make_keys.c -Wl,-rpath,/opt/graylog/embedded/lib -L/opt/graylog/embedded/lib   
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/lib_gen.c -o ../obj_s/lib_gen.o
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./base/lib_initscr.c -o ../obj_s/lib_initscr.o
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./base/lib_insch.c -o ../obj_s/lib_insch.o
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./base/lib_insdel.c -o ../obj_s/lib_insdel.o
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./base/lib_insnstr.c -o ../obj_s/lib_insnstr.o
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./base/lib_instr.c -o ../obj_s/lib_instr.o
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./base/lib_isendwin.c -o ../obj_s/lib_isendwin.o
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./base/lib_leaveok.c -o ../obj_s/lib_leaveok.o
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./base/lib_mouse.c -o ../obj_s/lib_mouse.o
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./base/lib_move.c -o ../obj_s/lib_move.o
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -I/opt/graylog/embedded/include -I/opt/graylog/embedded/include  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./tty/lib_mvcur.c -o ../obj_s/lib_mvcur.o
Makefile:1188: recipe for target '../obj_s/lib_gen.o' failed
make[1]: Leaving directory '/var/cache/omnibus/src/ncurses-5.9/ncurses'
Makefile:109: recipe for target 'all' failed
STDERR: In file included from ../ncurses/curses.priv.h:283:0,
                 from ../ncurses/lib_gen.c:19:
_27633.c:1364:15: error: expected ')' before 'int'
../include/curses.h:1906:56: note: in definition of macro 'mouse_trafo'
 #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                        ^
make[1]: *** [../obj_s/lib_gen.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
---- End output of make -j 9 ----
Ran make -j 9 returned 2
	from /var/lib/gems/2.1.0/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:259:in `error!'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/util.rb:84:in `shellout!'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:723:in `_shellout!'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:84:in `block in command'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:930:in `instance_eval'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:930:in `run'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:741:in `block (3 levels) in execute'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:766:in `call'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:766:in `with_retries'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:740:in `block (2 levels) in execute'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/instrumentation.rb:23:in `call'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/instrumentation.rb:23:in `measure'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:739:in `block in execute'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:809:in `call'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:809:in `with_clean_env'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:738:in `execute'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:640:in `block (2 levels) in build'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:639:in `each'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:639:in `block in build'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/instrumentation.rb:23:in `call'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/instrumentation.rb:23:in `measure'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/builder.rb:638:in `build'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/software.rb:981:in `execute_build'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/software.rb:844:in `build_me'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/project.rb:973:in `block in build_me'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/project.rb:972:in `each'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/project.rb:972:in `build_me'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/cli.rb:72:in `build'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/cli/base.rb:33:in `dispatch'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/cli/deprecated.rb:128:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/lib/omnibus/cli.rb:41:in `execute!'
	from /var/lib/gems/2.1.0/gems/omnibus-3.2.2/bin/omnibus:11:in `<top (required)>'
	from bin/omnibus:16:in `load'
	from bin/omnibus:16:in `<main>'

**Comment by mariussturm** [comment]
Please make sure to use the latest stable branch 1.3 and build the package on an Ubuntu host. You also need the following build dependencies: `git build-essential autoconf ruby2.0 ruby2.0-dev unzip`

**Comment by Aleyasen** [comment]
Thanks for the quick reply. 
Can I use the below Ubuntu version:
$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

**Comment by mariussturm** [comment]
We build on the LTS release 14.04. Possible that this is the problem.

**Comment by Aleyasen** [comment]
Thanks for your reply. I used the latest stable branch 1.3 and install the dependencies, but still I got the error. It seems ncurses has some compatibility issue with some version of gcc (e.g. https://github.com/cloudius-systems/osv/issues/634) . Could you please let me know which gcc version you use? 

If using the new gcc doesn't work, I have to use LTS release 14.04 :(

btw, in the latest branch 1.3 the md5 checksum for kopf is not match (config/software/kopf.rb). The new one is md5: "d5829ecaba16ead444fe3a233f58be42"

**Comment by joschi** [comment]
@Aleyasen We're using the default version from Ubuntu 14.04 LTS, which is GCC 4.8.2: http://packages.ubuntu.com/trusty/gcc

**Comment by Aleyasen** [comment]
Thanks for your reply. I used Ubuntu 14.04 and it worked perfectly :)
I have another question that I am not sure I should ask here or not. For this version (Graylog 1.3.3) for web-interface the source came from which repo?(and which branch?)

1- https://github.com/Graylog2/graylog2-server/tree/master/graylog2-web-interface
2- https://github.com/Graylog2/graylog2-web-interface

I know the second one is deprecated (after 1.3) but I am not sure for 1.3.3. Thanks.

**Comment by joschi** [comment]
@Aleyasen The repository for the web interface in Graylog 1.x is https://github.com/Graylog2/graylog2-web-interface

In general, please use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) for any issues and questions which aren't bug reports or feature requests.

**Comment by Aleyasen** [comment]
Sure, Thanks :-)
