### ISSUE TITLE
Old Log4j configuration file

### ISSUE THREAD

**Issue by joschi** [Graylog2/omnibus-graylog2#27]
The Log4j configuration file being used in the omnibus package (from the template [log4j.xml.erb](https://github.com/Graylog2/omnibus-graylog2/blob/41b7455a61de15efb043c352e40dce59f711a5bf/files/graylog-cookbooks/graylog/templates/default/log4j.xml.erb)) is still in the old format for Log4j 1.2 whereas Graylog 2.0.0 switched to Log4j 2 some time ago.

Refs Graylog2/graylog2-server#1804

**Comment by mariussturm** [comment]
Thanks, fixed!
