### ISSUE TITLE
Indexing issues cause appliance disk to fill up

### ISSUE THREAD

**Issue by dgerdem** [Graylog2/omnibus-graylog2#29]
In reference to Google groups thread: https://groups.google.com/forum/?hl=en#!topic/graylog2/dIJZF2REWPk

**Graylog version:**  latest version running on graylog appliance.  This issue has appeared in all versions of graylog that I have used.
**Graylog configurations:**  graylog appliance in question is only consuming Windows logs sent from NXlog (nxlog.conf file attached).  Approximately 300 messages per second.  Only additional configuration on the appliance is to limit the number of indices to 7 and their size to 1GB.
**Issue:**  Disk fills up and the system becomes unresponsive.  If this is caught while it is happening, indexer failures can be seen in the web console, and the journal file may be completely filled. Processing of incoming messages fails.  It fails at irregular intervals; the last time it happened it cycled successfully through 124 indices.  The log for the day it failed  (/var/log/graylog/elasticsearch folder the graylog.log.<date> ) was 2.1GB in size instead of the usual ~400KB.  Index folder size for the day it failed was 2.8GB instead of the usual 1GB.  Each shard folder had a large transaction log file of ~700MB.  i believe the combination of these fills up the disk before the log rotation or some other remediation can occur.
**Workaround:**  My current workaround is to run sudo graylog-ctl cleanse and reconfigure the appliance.  In the past, if the indexer failures are caught in time, the issue can be resolved by manually cycling the deflector.  This fix is temporary as it will eventually happen again.

[nxlog.txt](https://github.com/Graylog2/omnibus-graylog2/files/291213/nxlog.txt)

**Comment by dgerdem** [comment]
another note on this...I caught it in the act, before the disk could fill up.  It looked like processing of incoming messages had hung up, causing the journal to fill up and accumulate about 1 million messages.  I ran graylog-ctl restart stopped the inputs to let it catch up.  It started processing journal messages at a rate of about 1000 msg/sec.

**Comment by mariussturm** [comment]
I think the main problem is that the ES log files are rotated on a daily basis. When it comes to a short spike the log file can grow to a state where the disk runs out. I changed the ES logging configuration to rotate the log files based on size, so that it will never grow much more then 30MB.
The size of the ES indicies is something that ES itself takes care of, users have to make sure that they have some space left for the mentioned strechings.
ee0e46f6e81ca2ace0148b26a9b92ccdb9bc7028 should fix this.
