### ISSUE TITLE
Fresh install, Graylog2-server not listening (port 12900)

### ISSUE THREAD

**Issue by LordMike** [Graylog2/omnibus-graylog2#3]
On a fresh install of the omnibus package, the graylog2 server is not listening on 12900. The login page therefore shows "No Graylog2 servers available. Cannot log in.".

I have run graylog2-ctl and set an admin password and run "reconfigure". 

It seems that the 5 (necessary) services are running under the graylog2 user account:
- etcd
- mongod
- java/elasticsearch
- java/graylog2-server
- java/graylog2-web

The graylog2-server is set to run with a config from /opt/graylog2/conf/graylog2.conf, which states the following - which I take as configuration has been done correctly:

    ...
    rest_listen_uri = http://0.0.0.0:12900/
    ...

**Comment by LordMike** [comment]
Works in Ubuntu 14.04 LTS as expected.

**Comment by mariussturm** [comment]
Thanks!

**Comment by LordMike** [comment]
Still relevant as pr. #2, to note that if and when a build environment is set up for Debian, this should be fixed.

**Comment by wilson0x4d** [comment]
What is the impact, the final comment on this thread suggests graylog2 cannot be built and/or deployed successfully to a Debian host?

**Comment by bernd** [comment]
@wilson0x4d This repository is for the omnibus Graylog package which has been tailored for Ubuntu and is used for the appliance images. (OVA, Docker, ...) We offer official packages for Debian, Ubuntu and CentOS in our operating system repositories.

See: http://docs.graylog.org/en/1.2/pages/installation/operating_system_packages.html

**Comment by mbazyar** [comment]
@brend But I did not get it worked :(

**Comment by mbazyar** [comment]
I had the same problem and it fixed up as soon as I get the mongodb ip adress corrected.
