### ISSUE TITLE
security properties can't be set with advanced attributes

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/omnibus-graylog2#31]
according to [the advanced attributs](https://github.com/Graylog2/omnibus-graylog2/blob/1.3/files/graylog-cookbooks/graylog/attributes/default.rb) it is not possible to set Java OPS for [disable specific TLS ciphers](http://docs.graylog.org/en/2.0/pages/configuration/https.html#disabling-specific-tls-ciphers-and-algorithms).

This should be an additional option to set `-Djava.security.properties=`

**Comment by mariussturm** [comment]
Can now be done with something like:
```
"custom_attributes": {
    "graylog-server": {
      "java_opts": "-Djava.security.properties=/etc/sysconfig/jvm.java.security"
    }
  }
```
https://github.com/Graylog2/omnibus-graylog2/commit/b693b37b18b2dff10495338649035a1e2befa737
