### ISSUE TITLE
Missing installation note about graylog user

### ISSUE THREAD

**Issue by CharlieEriksen** [Graylog2/omnibus-graylog2#32]
I tried to install omnibus on a clean VM where the default ubuntu user was called "graylog". When trying to reconfigure graylog, it gives an error:

```
[2016-07-12T09:06:31+00:00] ERROR: user[graylog] (graylog::users line 11) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '8'
---- Begin output of ["usermod", "-s", "/bin/sh", "-d", "/var/opt/graylog", "graylog"] ----
STDOUT:
STDERR: usermod: user graylog is currently used by process 43714
---- End output of ["usermod", "-s", "/bin/sh", "-d", "/var/opt/graylog", "graylog"] ----
Ran ["usermod", "-s", "/bin/sh", "-d", "/var/opt/graylog", "graylog"] returned 8
```

I guess this is because the shell it's being run from is a sudo su-ed shell from the graylog user. 

Should the documentation for this maybe suggest that you don't set up an user called graylog when deploying your machine, such that the graylog user is handled by omnibus? Or is there maybe some solution, so this scenario is possible?

**Comment by mariussturm** [comment]
Hi Charlie,
I have put a node about this in the readme. As a non-graylog user the installation should work fine.
