### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by dlancea** [Graylog2/omnibus-graylog2#34]
Has this release been tested for Ubuntu 16.04 at all?

Are there any plans to upgrade the Graylog appliance to Ubuntu 16.04?

Thanks

**Comment by mariussturm** [comment]
We use the omnibus package only for the Graylog appliances and they are shipped with Ubuntu 14.04. There is no urgent need for us to port it to 16.04 so it's not tested and not planned for the next 1 or 2 iterations.
