### ISSUE TITLE
Reconfigure failed with Connection refused after upgrade to 2.2.3-1

### ISSUE THREAD

**Issue by eduanb** [Graylog2/omnibus-graylog2#38]
Hi,
I am logging a ticket here as suggested here [https://github.com/Graylog2/graylog2-cookbook/issues/88](url). The Graylog web server did not start up after running `sudo graylog-ctl reconfigure`.
I have tried to kill the etcd process which is holding the port but did not work. My guess is that the cookbook starts etcd before it should.
This is just after upgrading from 2.2.2-1 to 2.2.3-1

It doesn't seem like etcd is running as it should:
```
ubuntu@graylog:/$ sudo /opt/graylog/embedded/bin/etcdctl ls
Error:  client: etcd cluster is unavailable or misconfigured
error #0: read tcp 127.0.0.1:51776->127.0.0.1:4001: read: connection reset by peer
error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused
```

I have attached the stacktrace.

**Comment by mariussturm** [comment]
Is there an error in the etcd logs?

**Comment by eduanb** [comment]
This is repeated over and over (about every second) in /var/log/graylog/etcd/current
[etcd.txt](https://github.com/Graylog2/omnibus-graylog2/files/902393/etcd.txt)

**Comment by mariussturm** [comment]
Looks like your etcd database got corrupted. Maybe there was out of disk space condition or a hard crash. It this is a single node installation please stop etcd, remove the data files and restart it again:

```
sudo graylog-ctl stop etcd
# maybe check with `ps` and `kill -9` that the process is actually gone
sudo rm -r /var/opt/graylog/data/etcd/*
sudo graylog-ctl start etcd
sudo graylog-ctl reconfigure
```

**Comment by eduanb** [comment]
Thanks that worked. The web UI started up. Not sure why etcd was corrupted.
What is stored in /var/opt/graylog/data/etcd/? Is it something of value?

**Comment by mariussturm** [comment]
The appliance is storing the cluster configuration there like which node is the master or how many ES nodes are connected. Not important when all runs an the same machine. You can browse the data with `etcdctl`.
