### ISSUE TITLE
Ctl command, data location

### ISSUE THREAD

**Issue by LordMike** [Graylog2/omnibus-graylog2#4]
Hi there,

I think the ctl application is lacking some features, f.ex. on how to control where the data is stored. Either it should go as a seperate command, or it should be possible to configure some cenralized config file (applied using reconfigure).

- Mike

**Comment by mariussturm** [comment]
Hi Mike,
could you explain what scenario you try to solve? Not sure if I get this feature request right.

**Comment by LordMike** [comment]
I've installed the virtual appliance you have (the same goes for omnibus installs), and I prefer having OS and data separated. Because of that, I now have a data mount at eg. /mnt/data, but the mongodb & elasticsearch are at /Var/opt/graylog2. 

I could work around it by mounting at /var/opt/.., but I'd rather not :).

Other options that could be tweaked could be the indice sizes and counts, to name a few.

**Comment by mariussturm** [comment]
Ah I see. For this reason we especially choose to put all data in one directory. So MongoDB and Elasticsearch data are not spread around the whole system. This configuration makes it easy to extemd the data space, simply mount a new drive under /var/opt/graylog/data.

The appliance and the omnibus package are meant as a setup with good default values for an easy start, if you want full control over your installation please take a look at our Chef/Puppet recipes: https://github.com/Graylog2/graylog2-cookbook , https://github.com/Graylog2/graylog2-puppet
There you can configure much more details of your installation.

**Comment by LordMike** [comment]
I see. I'll do so :).
