### ISSUE TITLE
Command to re-enable all services

### ISSUE THREAD

**Issue by joschi** [Graylog2/omnibus-graylog2#40]
If a user configured the system to only run a subset of services, e. g. via the `reconfigure-as-backend` or `reconfigure-as-datanode` commands, it's currently not possible to re-enable all services without manually editing the `/etc/graylog/graylog-services.json` file.

The `graylog-ctl` utility should provide a command to re-enable all services.

**Comment by mariussturm** [comment]
Added a `graylog-ctl enable-all-services` command here: https://github.com/Graylog2/omnibus-graylog2/commit/f0c60c5b52095a0b5223bf4c787f52246d45da11
