### ISSUE TITLE
Update nginx

### ISSUE THREAD

**Issue by joschi** [Graylog2/omnibus-graylog2#41]
The version of nginx used in the Omnibus package ([version 1.9.14 as of now](https://github.com/Graylog2/omnibus-graylog2/blob/2.3.0-rc.2-2/config/software/nginx.rb#L2)) is quite old now and should be updated.

Related forum topic: https://community.graylog.org/t/nginx-vulnerability/1774

**Comment by mariussturm** [comment]
Fixed in https://github.com/Graylog2/omnibus-graylog2/commit/2fabb663cafe70a1a376768dd1e3395c4d0069b4
