### ISSUE TITLE
MongoDB cluster configuration

### ISSUE THREAD

**Issue by lcaflc** [Graylog2/omnibus-graylog2#49]
Hi,

I've setup a clustered graylog infrastructure using the omnibus installation of graylog which is really nice for our usage. However it remains the mongodb part which is not managed by yourself because it's a little bit tricky to implement. I totally agree on it so I'll not request a fully automatic management of that. However even if we have setup the mongodb cluster we are unable to easily and cleanly run it.

We have to modify `/opt/graylog/conf/graylog.conf` with the complete mongodb_uri connection string of this form: 
```
mongodb_uri = mongodb://graylog:XXXX@185.169.89.80:27017,185.169.89.81:27017/graylog@?replicaSet=rs42
```
And add options to the mongodb service start command in `/opt/graylog/service/mongodb/run`
```
exec chpst -P -U graylog -u graylog /opt/graylog/mongodb/bin/mongod --dbpath /var/opt/graylog/data/mongodb --smallfiles  --bind_ip 0.0.0.0 --auth --keyFile /etc/graylog/mongodb.keyfile --replSet rs42
```

As the `graylog-ctl` override them, at each deployment we need to modify them by hand which is really not nice. 
It could be really nice to just implement some override options in the chef recipes / templates for these configuration so we can make them persistent.

Thanks.

**Comment by mariussturm** [comment]
In the next beta you can specify your own start up and connection options. Just put something like this in `/etc/graylog/graylog-settings.json`:

```
"custom_attributes": {
    "mongodb": {
      "additional_options": "--auth --keyFile /etc/graylog/mongodb.keyfile --replSet rs42",
      "uri": "mongodb://graylog:XXXX@185.169.89.80:27017,185.169.89.81:27017/graylog@?replicaSet=rs42"
    }
  }
```

and re-run `graylog-ctl reconfigure`.

Because this is a bit out of scope of the appilances there will be no `graylog-ctl` command for this. For more customization options consider an installation based on DEB/RPMs.

05fad2227211cc1bd10ac438f531332f0155e2db

**Comment by lcaflc** [comment]
This is awesome ! Thanks.
