### ISSUE TITLE
SSL/TLS for SMTP should be configurable

### ISSUE THREAD

**Issue by joschi** [Graylog2/omnibus-graylog2#5]
The `transport_email_use_tls` and `transport_email_use_ssl` settings in Graylog's configuration file should be configurable. Currently they're hard coded to `true`: https://github.com/Graylog2/omnibus-graylog2/blob/1.0.0-5/files/graylog-cookbooks/graylog/templates/default/graylog.conf.erb#L231-232

Related post on mailing list: https://groups.google.com/forum/#!topic/graylog2/EcsNdAy87jU

**Comment by mariussturm** [comment]
Fixed in current OVA. Can be disabled with `graylog-ctl set-email-config ... --no-tls --no-ssl`
