### ISSUE TITLE
api-browser not working in OVA appliances due to nginx missconfig

### ISSUE THREAD

**Issue by radykal-com** [Graylog2/omnibus-graylog2#50]
Hello,

coming from https://github.com/Graylog2/graylog2-server/issues/3519

There is an issue with the api-browser not working when using the nginx reverse proxy. I have tracked it down to this https://github.com/Graylog2/graylog2-server/issues/3519#issuecomment-336365380

The fix is easy to apply for new setups, I can make the PR with it, but I was wondering if there is any chance to patch some versions along latest, so people installing older versions can have the fix also.

**Comment by mariussturm** [comment]
Thanks for the investigation! I have merged it into the last two major versions (2.2 and 2.3). Upgraded omnibus packages are available for download (2.2.3-4, 2.3.1-4): https://packages.graylog2.org/appliances/ubuntu

**Comment by radykal-com** [comment]
Thanks you!
