### ISSUE TITLE
AWS ami enforce-ssl problem

### ISSUE THREAD

**Issue by codezero** [Graylog2/omnibus-graylog2#56]
I upgraded my box to 2.3.2 and after the upgrade I started to get 404 - cannot POST https://IPADRESS/api/system/sessions. So I started from a fresh AMI(2.3.2-2) and followed just these steps as described in the documentation:

sudo graylog-ctl enforce-ssl
sudo graylog-ctl reconfigure
sudo graylog-ctl set-external-ip https://ip:443/api
sudo graylog-ctl reconfigure

and the result is the same. It cannot access to the API.

**Comment by mariussturm** [comment]
This should be fixed in version 2.3.2-3. Either download the omnibus package and update your current installation or start from scratch with a new ami.
