### ISSUE TITLE
Unable to access graylog web console

### ISSUE THREAD

**Issue by bmillertri** [Graylog2/omnibus-graylog2#57]
Cannot open web console.

Ran the cmd to check what services are running - sudo graylog-ctl status

Both etcd and mongodb are down 

I have tried to start them and can get etcd started for a minute but then it goes down again.

I have no experience with this interface and hope someone can help me get this back online.  What information can I provide to help?

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
