### ISSUE TITLE
Incorrect setting of local_connect in graylog_settings.json

### ISSUE THREAD

**Issue by ArchitectAdam** [Graylog2/omnibus-graylog2#6]
I built a 2 node graylog setup with a master server and a web node via docker using the -e variables to denote which was a server and which was web etc.

When I fire up the graylog web container it will not connect to the graylog server as it has an incorrect setting in the graylog_settings.json file. It is setting local_connect to true instead of false. Once I ssh into the container and change the local_connect variable to false and reconfigure it then connects straight away to the server with no other changes.

I think this is down to line 150 in omnibus-graylog2/files/graylog-cookbooks/graylog/libraries/graylog.rb.

**Comment by mariussturm** [comment]
Thanks, should be fixed with this commit: https://github.com/Graylog2/omnibus-graylog2/commit/2d179cd8c55794cfc24e5e8c215f439162c75db6
Could you please pull the latest container and try again?

**Comment by ArchitectAdam** [comment]
Yes that has fixed it. Thank you for the very quick turnaround.
